# Common Libraries

In [1]:
import os, sys, optax
import numpy as np
import pandas as pd
import equinox as eqx
from tqdm import tqdm, trange
import matplotlib.pylab as plt
from typing import Tuple, Dict

"""
Setting for GPU acceleration
"""
os.environ.setdefault("MUJOCO_GL", "egl")
os.environ.setdefault("PYOPENGL_PLATFORM", "egl")
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false" # limit jax and TF from consuming all GPU memory

# Jax
import jax
jax.config.update("jax_enable_x64", True)
from jax import numpy as jnp
from jaxtyping import Float, Array

# Mujoco
import mujoco

# Custom Libraries

In [2]:
sys.path.append("/home/seojin/Tools/biomechanics/MonocularBiomechanics")
from monocular_demos.biomechanics_mjx.forward_kinematics import ForwardKinetics
from monocular_demos.biomechanics_mjx.monocular_trajectory import KineticsWrapper

In [3]:
# construct a loss function between the forward pass through the forward kinematic
# implicit representation and the resulting keypoint and the detected keypoitns
def loss(
    model: KineticsWrapper,
    x: Float[Array, "times"],
    y: Float[Array, "times keypoints 3"],
    target_site_idx,
    site_offset_regularization = 1e-1
) -> Tuple[Float, Dict]:

    timestamps = x
    keypoints3d = y # unit: m
    metrics = {}

    # NOTE: steps is an make sure this retraces for different dimensions
    (state, constraints, next_states), (ang, vel, action), _ = model(
        timestamps,
        skip_vel=True,
        skip_action=True,
    )

    pred_kp3d = state.site_xpos[:, target_site_idx, :] # unit: m, shape: (#datas, #sites, 3)
    l = jnp.mean((pred_kp3d - keypoints3d) ** 2) * 100 # so in cm
    metrics["kp_err"] = l

    # regularize marker offset
    l_site_offset = jnp.sum(jnp.square(model.site_offsets))
    l += l_site_offset * site_offset_regularization

    # make loss the first key in the dictionary by popping and building a new dictionary with the rest
    metrics = {"loss": l, **metrics}

    return l, metrics

@eqx.filter_jit
def step(model, opt_state, data, loss_grad, optimizer, **kwargs):
    x, targets = data

    (val, metrics), grads = loss_grad(model, x=x, y=targets, **kwargs)
    updates, opt_state = optimizer.update(grads, opt_state, eqx.filter(model, eqx.is_inexact_array))
    model = eqx.apply_updates(model, updates) # Update model with preserving immutable property
    
    return val, model, opt_state, metrics

# Params

In [4]:
model_path = "/mnt/sdb2/DeepProprioception/MyoSuite/muscle_mimic/muscle_mimic_scaled.xml"
pose3d_path = "/mnt/ext1/seojin/temp/DP/Rendering/output/smplv2/smpl_pose_run1.npz"

# Constants

In [5]:
# SMPL <-> Muscle Mimic body name
mapping_smpl_mm = {
    "R_Shoulder" : "humerus_r",
    "R_Elbow" : "ulna_r",
    "R_Wrist" : "lunate_r",
}

# Make model

In [6]:
fk = ForwardKinetics(xml_path = model_path)

actuator_names = np.array([mujoco.mj_id2name(fk.model, mujoco.mjtObj.mjOBJ_ACTUATOR, i) for i in range(fk.model.nu)])

body_names = np.array([mujoco.mj_id2name(fk.model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(fk.model.nbody)])
excludes = ["world", "Bimanual", "root"]
body_segment_names = body_names[np.isin(body_names, excludes) == False]

site_names = np.array([mujoco.mj_id2name(fk.model, mujoco.mjtObj.mjOBJ_SITE, i) for i in range(fk.model.nsite)])

mimic_site_idx = jnp.array([fk.site_names.index(f"{name}_Mimic_Site") for name in mapping_smpl_mm])

# Make scale mix

Each key in mappings represents a segment group, and the corresponding list contains the subsegments belonging to that group

In [7]:
# Scale mix
mappings = {
    "torso" : ["thorax", "cervical_spine"],
    "shoulder_r" : ["clavicle_r", "scapula_r"],
    "upperarm_r" : ["humerus_r"],
    "forearm_r" : ["radius_r", "ulna_r"],
    "overall" : body_segment_names,
}

scale_mixer = jnp.array([
    [1.0 if body in child_segments else 0.0 
     for segment, child_segments in mappings.items()]
    for body in body_names
])

In [8]:
"""
KineticsWrapper consists of a neural network and a forward kinematics module, 
    where the scaling factor for each body segment is computed from body_scale and scale_mixer

Property
    - NonLearnable
        - scale_mixer

    - Learnable
        - body_scale
        - site_offsets: offset of each site
"""
model = KineticsWrapper(fk, scale_mixer = scale_mixer)

/tmp/ipykernel_510364/1986745145.py:13: UserWarning: A JAX array is being set as static! This can result in unexpected behavior and is usually a mistake to do.
  model = KineticsWrapper(fk, scale_mixer = scale_mixer)

# Load data & Preprocessing

In [9]:
# Load pose
smpl_data = np.load(pose3d_path)
pose3d = smpl_data["kp3ds"]
kp_labels = list(smpl_data["kp_label"])
pose3d = pose3d[:10, :, :]

# Filtering
target_smpl_kp_idx = [ kp_labels.index(smpl_kp) for smpl_kp in mapping_smpl_mm ]
pose3d = pose3d[:, target_smpl_kp_idx, :]

# Make dataset
timestamps = jnp.arange(len(pose3d)) / 30.0
dataset = (timestamps, pose3d)

# Calculate loss

In [10]:
results = model(timestamps, skip_vel = True, skip_action = True)

kinetics_output = results[0]
trajectory_output = results[1]

state = kinetics_output[0]
constraints = kinetics_output[1]
next_states = kinetics_output[2]

joint_angle = trajectory_output[0]
joint_velocity = trajectory_output[1]
action = trajectory_output[2]

In [11]:
pred_kp3d = state.site_xpos[:, mimic_site_idx, :]
correct_kp3d = dataset[1]

In [12]:
site_offset_regularization = 1e-1

In [13]:
l = jnp.mean((pred_kp3d - correct_kp3d) ** 2) * 100 # so in cm

metrics = {}
metrics["kp_err"] = l

# regularize marker offset
l_site_offset = jnp.sum(jnp.square(model.site_offsets))
l += l_site_offset * site_offset_regularization

In [14]:
# make loss the first key in the dictionary by popping and building a new dictionary with the rest
metrics = {"loss": l, **metrics}

# Fit model

In [15]:
lr_end_value = 1e-8
lr_init_value = 1e-4
max_iters: int = 5000
clip_by_global_norm = 0.1

In [16]:
# work out the transition steps to make the desired schedule
transition_steps = 10
lr_decay_rate = (lr_end_value / lr_init_value) ** (1.0 / (max_iters // transition_steps))
learning_rate = optax.warmup_exponential_decay_schedule(
    init_value=0,
    warmup_steps=0,
    peak_value=lr_init_value,
    end_value=lr_end_value,
    decay_rate=lr_decay_rate,
    transition_steps=transition_steps,
)

In [17]:
optimizer = optax.chain(
    optax.adamw(learning_rate=learning_rate, b1=0.8, weight_decay=1e-5),
    optax.zero_nans(),
    optax.clip_by_global_norm(clip_by_global_norm)
)

In [18]:
opt_state = optimizer.init(eqx.filter(model, eqx.is_inexact_array))

In [19]:
loss_grad = eqx.filter_value_and_grad(loss, has_aux=True)

In [ ]:
counter = trange(max_iters)
for i in counter:
    # val, model, opt_state, metrics = step(model, opt_state, dataset, loss_grad, optimizer)
    
    x, targets = dataset
    (loss, metrics), gradients = loss_grad(model, x=x, y=targets, target_site_idx = mimic_site_idx) # metrics: auxiliary data
    updates, opt_state = optimizer.update(gradients, opt_state, eqx.filter(model, eqx.is_inexact_array))
    model = eqx.apply_updates(model, updates)

    # Print optimization result
    if i > 0 and i % int(max_iters // 10) == 0:
        print(f"iter: {i} loss: {loss}.")  # metrics: {metrics}")

    if i % 50 == 0:
        metrics = {k: v.item() for k,v in metrics.items()}
        print(loss, metrics)

  0%|          | 1/5000 [00:23<33:01:17, 23.78s/it]

823.9043088119381 {'kp_err': 823.9043088106348, 'loss': 823.9043088119381}

  1%|          | 51/5000 [00:41<27:39,  2.98it/s]

73.18303613004562 {'kp_err': 73.18303127001093, 'loss': 73.18303613004562}

  2%|▏         | 101/5000 [01:01<28:56,  2.82it/s]

63.71266705177126 {'kp_err': 63.71264833490647, 'loss': 63.71266705177126}

  3%|▎         | 151/5000 [01:19<28:25,  2.84it/s]

59.962832428099944 {'kp_err': 59.96279357036796, 'loss': 59.962832428099944}

  4%|▍         | 201/5000 [01:38<27:48,  2.88it/s]

57.072759495713456 {'kp_err': 57.07269637414959, 'loss': 57.072759495713456}

  5%|▌         | 251/5000 [01:57<28:26,  2.78it/s]

54.56074430212312 {'kp_err': 54.56065422193923, 'loss': 54.56074430212312}

  6%|▌         | 301/5000 [02:16<28:09,  2.78it/s]

52.34678570976829 {'kp_err': 52.34666707924153, 'loss': 52.34678570976829}

  7%|▋         | 351/5000 [02:36<28:26,  2.72it/s]

50.381988954699644 {'kp_err': 50.381841028807386, 'loss': 50.381988954699644}

  8%|▊         | 401/5000 [02:56<27:52,  2.75it/s]

48.63588674597462 {'kp_err': 48.63570942133027, 'loss': 48.63588674597462}

  9%|▉         | 451/5000 [03:17<30:29,  2.49it/s]

47.078121341648426 {'kp_err': 47.07791499229817, 'loss': 47.078121341648426}

 10%|█         | 501/5000 [03:37<29:17,  2.56it/s]

iter: 500 loss: 45.68638739053785.
45.68638739053785 {'kp_err': 45.68615273840133, 'loss': 45.68638739053785}

 11%|█         | 551/5000 [03:56<27:26,  2.70it/s]

44.43963716690246 {'kp_err': 44.43937517977797, 'loss': 44.43963716690246}

 12%|█▏        | 601/5000 [04:16<26:58,  2.72it/s]

43.321386946528165 {'kp_err': 43.32109875893092, 'loss': 43.321386946528165}

 13%|█▎        | 651/5000 [04:36<26:37,  2.72it/s]

42.31630672502252 {'kp_err': 42.31599357723812, 'loss': 42.31630672502252}

 14%|█▍        | 701/5000 [04:56<26:08,  2.74it/s]

41.41065941695931 {'kp_err': 41.410322609083124, 'loss': 41.41065941695931}

 15%|█▌        | 751/5000 [05:18<34:21,  2.06it/s]

40.594968578223416 {'kp_err': 40.59460943365794, 'loss': 40.594968578223416}

 16%|█▌        | 801/5000 [05:39<28:32,  2.45it/s]

39.857688931706946 {'kp_err': 39.857308770604924, 'loss': 39.857688931706946}

 17%|█▋        | 851/5000 [06:00<27:28,  2.52it/s]

39.191685503773414 {'kp_err': 39.19128562472617, 'loss': 39.191685503773414}

 18%|█▊        | 901/5000 [06:21<27:28,  2.49it/s]

38.58895598260685 {'kp_err': 38.588537648220914, 'loss': 38.58895598260685}

 19%|█▉        | 951/5000 [06:42<26:47,  2.52it/s]

38.0426534019247 {'kp_err': 38.042217829181986, 'loss': 38.0426534019247}

 20%|██        | 1001/5000 [07:03<26:17,  2.54it/s]

iter: 1000 loss: 37.54706707039093.
37.54706707039093 {'kp_err': 37.54661542409256, 'loss': 37.54706707039093}

 21%|██        | 1051/5000 [07:24<26:03,  2.53it/s]

37.09674051430116 {'kp_err': 37.09627390325437, 'loss': 37.09674051430116}

 22%|██▏       | 1101/5000 [07:46<25:31,  2.55it/s]

36.68734030072954 {'kp_err': 36.68685977582562, 'loss': 36.68734030072954}

 23%|██▎       | 1151/5000 [08:07<25:19,  2.53it/s]

36.31475609488283 {'kp_err': 36.31426264847771, 'loss': 36.31475609488283}

 24%|██▍       | 1201/5000 [08:28<25:24,  2.49it/s]

35.9754034125981 {'kp_err': 35.97489797877381, 'loss': 35.9754034125981}

 25%|██▌       | 1251/5000 [08:50<25:37,  2.44it/s]

35.666089133106006 {'kp_err': 35.66557258897722, 'loss': 35.666089133106006}

 26%|██▌       | 1301/5000 [09:12<25:52,  2.38it/s]

35.38398777015689 {'kp_err': 35.3834609374824, 'loss': 35.38398777015689}

 27%|██▋       | 1351/5000 [09:34<25:07,  2.42it/s]

35.126585074733015 {'kp_err': 35.12604872202184, 'loss': 35.126585074733015}

 28%|██▊       | 1401/5000 [09:56<24:31,  2.45it/s]

34.8915929745174 {'kp_err': 34.891047819355535, 'loss': 34.8915929745174}

 29%|██▉       | 1451/5000 [10:18<23:50,  2.48it/s]

34.676957308611236 {'kp_err': 34.676404020080604, 'loss': 34.676957308611236}

 30%|███       | 1501/5000 [10:41<41:42,  1.40it/s]

iter: 1500 loss: 34.48089823787518.
34.48089823787518 {'kp_err': 34.48033743906512, 'loss': 34.48089823787518}

 31%|███       | 1551/5000 [11:03<26:24,  2.18it/s]

34.30168529985964 {'kp_err': 34.301117570414874, 'loss': 34.30168529985964}

 32%|███▏      | 1601/5000 [11:25<24:58,  2.27it/s]

34.137874490616305 {'kp_err': 34.137300369191884, 'loss': 34.137874490616305}

 33%|███▎      | 1651/5000 [11:47<22:56,  2.43it/s]

33.98813352143838 {'kp_err': 33.98755350810182, 'loss': 33.98813352143838}

 34%|███▍      | 1701/5000 [12:09<22:25,  2.45it/s]

33.851178430575516 {'kp_err': 33.850592989196706, 'loss': 33.851178430575516}

 35%|███▌      | 1751/5000 [12:31<22:23,  2.42it/s]

33.72595292816252 {'kp_err': 33.72536248862303, 'loss': 33.72595292816252}

 36%|███▌      | 1801/5000 [12:54<21:56,  2.43it/s]

33.61143717411816 {'kp_err': 33.610842134531566, 'loss': 33.61143717411816}

 37%|███▋      | 1851/5000 [13:16<21:48,  2.41it/s]

33.50667424568142 {'kp_err': 33.506074974430334, 'loss': 33.50667424568142}

 38%|███▊      | 1901/5000 [13:38<21:37,  2.39it/s]

33.410861924776235 {'kp_err': 33.41025876245602, 'loss': 33.410861924776235}

 39%|███▉      | 1951/5000 [14:02<36:36,  1.39it/s]

33.32323500415434 {'kp_err': 33.32262826550143, 'loss': 33.32323500415434}

 40%|████      | 2001/5000 [14:24<31:54,  1.57it/s]

iter: 2000 loss: 33.24307655039678.
33.24307655039678 {'kp_err': 33.242466526005046, 'loss': 33.24307655039678}

 41%|████      | 2051/5000 [14:47<22:17,  2.20it/s]

33.16975321299491 {'kp_err': 33.16914017099325, 'loss': 33.16975321299491}

 42%|████▏     | 2101/5000 [15:10<20:30,  2.36it/s]

33.102701719348616 {'kp_err': 33.10208590703723, 'loss': 33.102701719348616}

 43%|████▎     | 2151/5000 [15:32<20:45,  2.29it/s]

33.04138647713278 {'kp_err': 33.04076812240701, 'loss': 33.04138647713278}

 44%|████▍     | 2201/5000 [15:57<22:08,  2.11it/s]

32.985300246215864 {'kp_err': 32.9846795589842, 'loss': 32.985300246215864}

 45%|████▌     | 2251/5000 [16:20<19:37,  2.33it/s]

32.934017830435906 {'kp_err': 32.9333950039512, 'loss': 32.934017830435906}

 46%|████▌     | 2301/5000 [16:43<20:06,  2.24it/s]

32.887130109961646 {'kp_err': 32.886505322050084, 'loss': 32.887130109961646}

 47%|████▋     | 2351/5000 [17:06<18:45,  2.35it/s]

32.84424066484873 {'kp_err': 32.843614079041934, 'loss': 32.84424066484873}

 48%|████▊     | 2401/5000 [17:30<37:49,  1.15it/s]

32.80504063023242 {'kp_err': 32.80441239686154, 'loss': 32.80504063023242}

 49%|████▉     | 2451/5000 [17:53<20:53,  2.03it/s]

32.76918539830084 {'kp_err': 32.76855565550519, 'loss': 32.76918539830084}

 50%|█████     | 2501/5000 [18:15<19:45,  2.11it/s]

iter: 2500 loss: 32.7364046505305.
32.7364046505305 {'kp_err': 32.73577352518712, 'loss': 32.7364046505305}

 51%|█████     | 2551/5000 [18:38<17:52,  2.28it/s]

32.706440828944125 {'kp_err': 32.705808437546715, 'loss': 32.706440828944125}

 52%|█████▏    | 2601/5000 [19:01<17:13,  2.32it/s]

32.67907478938414 {'kp_err': 32.67844123884519, 'loss': 32.67907478938414}

 53%|█████▎    | 2651/5000 [19:24<16:45,  2.34it/s]

32.654024698774 {'kp_err': 32.653390087188264, 'loss': 32.654024698774}

 54%|█████▍    | 2701/5000 [19:47<16:20,  2.34it/s]

32.63114391601112 {'kp_err': 32.630508333361085, 'loss': 32.63114391601112}

 55%|█████▌    | 2751/5000 [20:10<16:01,  2.34it/s]

32.61024285492452 {'kp_err': 32.60960638370737, 'loss': 32.61024285492452}

 56%|█████▌    | 2801/5000 [20:33<15:46,  2.32it/s]

32.59111470015399 {'kp_err': 32.59047741598932, 'loss': 32.59111470015399}

 57%|█████▋    | 2851/5000 [20:56<15:15,  2.35it/s]

32.57367607858364 {'kp_err': 32.573038050775004, 'loss': 32.57367607858364}

 58%|█████▊    | 2901/5000 [21:19<14:52,  2.35it/s]

32.557691593505524 {'kp_err': 32.557052885555535, 'loss': 32.557691593505524}

 59%|█████▉    | 2951/5000 [21:42<14:28,  2.36it/s]

32.54311954616611 {'kp_err': 32.54248021623901, 'loss': 32.54311954616611}

 60%|██████    | 3001/5000 [22:05<14:16,  2.33it/s]

iter: 3000 loss: 32.52979021140733.
32.52979021140733 {'kp_err': 32.529150312766376, 'loss': 32.52979021140733}

 61%|██████    | 3051/5000 [22:27<13:41,  2.37it/s]

32.51761122236662 {'kp_err': 32.516970803776566, 'loss': 32.51761122236662}

 62%|██████▏   | 3101/5000 [22:50<13:38,  2.32it/s]

32.50649304846172 {'kp_err': 32.505852154571194, 'loss': 32.50649304846172}

 63%|██████▎   | 3151/5000 [23:13<13:12,  2.33it/s]

32.49632765719958 {'kp_err': 32.49568632886423, 'loss': 32.49632765719958}

 64%|██████▍   | 3201/5000 [23:36<13:19,  2.25it/s]

32.48704698298356 {'kp_err': 32.48640525759109, 'loss': 32.48704698298356}

 65%|██████▌   | 3251/5000 [24:00<12:30,  2.33it/s]

32.47857148775162 {'kp_err': 32.47792939951175, 'loss': 32.47857148775162}

 66%|██████▌   | 3295/5000 [24:21<12:15,  2.32it/s]

# Visualization

In [86]:
body_scale_vals = np.array(model.body_scale).flatten()
final_body_scales = (1.0 + np.array(model.scale_mixer) @ body_scale_vals).flatten()
body_names = ["world"] + list(model.forward.body_names)
scale_df = pd.DataFrame({
    "Segment": body_names,
    "Scale_Factor": final_body_scales,
})

scale_df

             Segment  Scale_Factor
0              world      1.000000
1           Bimanual      1.000000
2               root      1.000000
3             thorax      0.981886
4     cervical_spine      0.981886
5         clavicle_r      1.000299
6        clavphant_r      1.007672
7          scapula_r      1.000299
8        scapphant_r      1.007672
9         humphant_r      1.007672
10       humphant1_r      1.007672
11         humerus_r      1.026626
12            ulna_r      1.008286
13          radius_r      1.008286
14          lunate_r      1.007672
15        scaphoid_r      1.007672
16        pisiform_r      1.007672
17      triquetrum_r      1.007672
18        capitate_r      1.007672
19       trapezium_r      1.007672
20         firstmc_r      1.007672
21  proximal_thumb_r      1.007672
22    distal_thumb_r      1.007672
23       trapezoid_r      1.007672
24          hamate_r      1.007672
25        secondmc_r      1.007672
26         2proxph_r      1.007672
27          2midph_r      1.007672
28         2distph_r      1.007672
29         thirdmc_r      1.007672
30         3proxph_r      1.007672
31          3midph_r      1.007672
32         3distph_r      1.007672
33        fourthmc_r      1.007672
34         4proxph_r      1.007672
35          4midph_r      1.007672
36         4distph_r      1.007672
37         fifthmc_r      1.007672
38         5proxph_r      1.007672
39          5midph_r      1.007672
40         5distph_r      1.007672

In [87]:
offsets_mm = np.array(model.site_offsets[mimic_site_idx]) * 1000.0   # m -> mm 변환
total_shift_mm = np.linalg.norm(offsets_mm, axis=-1)

site_names = np.array(model.forward.site_names)[mimic_site_idx]

offset_df = pd.DataFrame({
    "Site_Name": site_names,
    "Offset_X (mm)": offsets_mm[:, 0],
    "Offset_Y (mm)": offsets_mm[:, 1],
    "Offset_Z (mm)": offsets_mm[:, 2],
    "Total_Shift (mm)": total_shift_mm
})

print("\n=== [2] 사이트(마커)별 오프셋 이동량 (이동량 큰 순서) ===")
display(offset_df.sort_values(by="Total_Shift (mm)", ascending=False))

=== [2] 사이트(마커)별 오프셋 이동량 (이동량 큰 순서) ===

,Site_Name,Offset_X (mm),Offset_Y (mm),Offset_Z (mm),Total_Shift (mm)
0,R_Shoulder_Mimic_Site,-53.036740,-51.562929,-9.767340,74.612548
1,R_Elbow_Mimic_Site,-0.370890,-29.225436,-2.133648,29.305564
2,R_Wrist_Mimic_Site,0.467559,-0.519699,-0.099152,0.706066